Ui buyer profile
noggalito/porttare-frontend pull request #114
Opened 2016-11-29 03:46 UTC by MarioRDuque

http://nodriza.noggalito.com/issues/802

2016-11-29 04:05 UTC, macool commented
necesita (primero) un rebase

2016-11-29 08:16 UTC, fabricioflores commented on Gemfile.lock
> +    ffi (1.9.10-x64-mingw32)
@macool que hacemos con esto?

2016-11-29 08:16 UTC, fabricioflores commented on app/styles/profile/profile.scss
> +  //tamaño header and espaciados
el código debe ser autoexplicativo. Sin comentarios

2016-11-29 08:17 UTC, fabricioflores commented on app/styles/profile/profile.scss
> +    //etiqueta que hace mencion al dato del comprador(Ej: "username:")
igual. Elimina los comentarios por favor

2016-11-29 11:28 UTC, macool commented on Gemfile.lock
> +    ffi (1.9.10-x64-mingw32)
@fabricioflores a la hoguera

2016-11-30 06:44 UTC, macool commented
@MarioRDuque en el rebase tienes que dejar sólo tus commits

2016-11-30 06:44 UTC, macool requested changes
rebase

2016-11-30 08:30 UTC, fabricioflores commented on app/styles/login/general.scss
> +}
falta una línea al final... instala el plugin de editorconfig en tu editor...

2016-11-30 08:30 UTC, fabricioflores commented on app/templates/profile/profile.jade
> +        img(src="images/camera.png", height=200)
no hay como poner la altura en una clase?

2016-11-30 21:41 UTC, macool commented on app/templates/profile/info/info.jade
> +      label.item.item-input.label-profile-buyer
una clase padre en lugar de todas estas hijas

2016-11-30 23:27 UTC, closed without merging