Feature #798
noggalito/porttare-frontend pull request #125
Opened 2016-11-30 17:10 UTC by craupesantez

se agrego un campo para especificar la cantidad que poseo en inventario y e toggle para indicar el producto en stock

2016-11-30 17:12 UTC, macool commented on app/scripts/controllers/items-controller.js
> +      itemsVm.item.cantidad=0;
esto es el default. podríamos borrar ^

2016-11-30 17:13 UTC, macool commented
@craupesantez puedes coger este branch del backend que agrega el campo https://github.com/noggalito/porttare-backend/pull/68/files

2016-11-30 17:30 UTC, macool commented on app/scripts/controllers/items-controller.js
> +    function stockNotification(){
el nombre necesita ser descriptivo

2016-11-30 17:33 UTC, macool commented on app/scripts/controllers/items-controller.js
> +      itemsVm.item.cantidad = !(itemsVm.item.enStock) ?  0 :  (itemsVm.item.cantidad ?  itemsVm.item.cantidad: 0);
el campo .enStock no existe - lo que hace este toggle es actualizar la cantidad a 0 (en el backend)

2016-11-30 17:35 UTC, macool commented on app/templates/item/new-edit.jade
> +            type='number'
controlamos el dominio? no negativos

2016-11-30 17:36 UTC, macool commented
y tienes conflictos

2016-12-03 10:41 UTC, fabricioflores commented on app/templates/item/new-edit.jade
> +        )
tienen un link a esta historia? no entiendo para q un toggle y pregunta el stock...

2016-12-04 21:14 UTC, macool commented on app/scripts/controllers/items-controller.js
> +      itemsVm.item.cantidad = !(itemsVm.item.en_stock) ?  0 :  (itemsVm.item.cantidad ?  itemsVm.item.cantidad: 0);
esto no debe hacer - stock y cantidad son cosas distintas

2016-12-04 21:16 UTC, macool commented on app/templates/item/new-edit.jade
> +        )
+1 @fabricioflores toggle y stock deben ser cosas distintas

2016-12-04 21:17 UTC, macool commented
nos falta el toggle en la vista del producto

2016-12-05 13:28 UTC, macool requested changes

2016-12-05 13:28 UTC, macool commented on app/scripts/controllers/items-controller.js
> +      itemsVm.item.cantidad = !(itemsVm.item.en_stock) ?  0 :  (itemsVm.item.cantidad ?  itemsVm.item.cantidad: 0); //jshint ignore:line
https://github.com/noggalito/porttare-frontend/pull/125#discussion_r90284537

2016-12-05 21:55 UTC, macool commented on app/scripts/controllers/items-controller.js
> +      itemsVm.item.en_stock=true; //jshint ignore:line
qué hace toda esta función?

2016-12-05 21:55 UTC, macool commented on app/templates/item/new-edit.jade
> +
sin whitespace

2016-12-05 21:56 UTC, macool commented on app/templates/item/new-edit.jade
> +          toggle-class='toggle-calm'
seguro que es toggle-calm?

2016-12-05 21:56 UTC, macool commented on app/templates/item/new-edit.jade
> +            span.input-label{{::("item.stock"|translate|uppercase)}}
sin uppercase

2016-12-06 14:08 UTC, craupesantez reviewed
@macool  así quedo... que cambios quieres q le haga aquí?
![image](https://cloud.githubusercontent.com/assets/5976040/20928351/7814d3ea-bb93-11e6-9e8c-afe4d43ef1ad.png)

2016-12-06 14:08 UTC, craupesantez commented on app/scripts/controllers/items-controller.js
> +      itemsVm.item.cantidad=0;
ok ya le borro

2016-12-06 14:08 UTC, craupesantez commented on app/templates/item/new-edit.jade
> +        )
http://nodriza.noggalito.com/issues/798

2016-12-06 14:08 UTC, craupesantez commented on app/scripts/controllers/items-controller.js
> +      itemsVm.item.en_stock=true; //jshint ignore:line
esa función inicializa a  en_stock en true xq si no, no se envía con el modelos si no lo le doy click en el toggle. 
(sin eso se enviara asi) 
![image](https://cloud.githubusercontent.com/assets/5976040/20904914/a16b8c86-bb0f-11e6-9398-e082ec3fb1d9.png)

y con esa funcion se enviara asi, aun si no le hubiera hecho click en el toggle
![image](https://cloud.githubusercontent.com/assets/5976040/20904826/39698c00-bb0f-11e6-96d3-72b147bf21a6.png)

2016-12-06 14:08 UTC, craupesantez commented on app/templates/item/new-edit.jade
> +          toggle-class='toggle-calm'
es solo diseño del toggle le voy ha dejar en toggle-energized, es de color amarillo

2016-12-07 08:12 UTC, fabricioflores commented
@craupesantez veo q la historia dice acerca de enviar algo al backend y no veo q maneja esto...

2016-12-07 16:39 UTC, closed without merging