Asignación de categorias en producto
noggalito/porttare-frontend pull request #126
Opened 2016-12-01 12:09 UTC by lglopezf

Utilizando la libreria selectize

2016-12-01 12:46 UTC, macool commented on app/scripts/controllers/items-controller.js
> +        create: false,
no es correcto

2016-12-01 12:52 UTC, macool commented on app/index.html
> +    <script src="bower_components/angular-selectize2/dist/angular-selectize.js"></script>
al parecer existe un "standalone" build en el que no tenemos que incluir todas estas

2016-12-01 12:53 UTC, macool commented on app/scripts/controllers/items-controller.js
> +      selectize();
tampoco veo tan bonito tener que inicializar las opciones :confused:

2016-12-01 12:54 UTC, macool commented on app/scripts/controllers/items-controller.js
> +        valueField: 'id',
déjalo para que se enlace a un endpoint del backend para yo leer esa solicitud y saber cómo filtrar/entregarte las categorías

2016-12-01 14:39 UTC, lglopezf commented on app/scripts/controllers/items-controller.js
> +        create: false,
Se puede crear categorías desde el producto?

2016-12-01 14:40 UTC, macool commented on app/scripts/controllers/items-controller.js
> +        create: false,
sí! p ej. el cliente puede introducir "productos de limpieza" si no existe en la lista

2016-12-01 14:41 UTC, macool commented on app/scripts/controllers/items-controller.js
> +        create: false,
si es un producto existente, se envía al backend su id. si el producto es nuevo tenemos que enviarlo como nested attribute - tenemos otras implementaciones para nested attribute p ej. con las imágenes de los productos

2016-12-01 14:42 UTC, lglopezf commented on app/scripts/controllers/items-controller.js
> +        valueField: 'id',
Okey, para consumir el endpoint que parámetros enviaría y que me retornaria para tener un poco mas claro el escenario.

2016-12-03 02:27 UTC, lglopezf commented on app/index.html
> +    <script src="bower_components/angular-selectize2/dist/angular-selectize.js"></script>
Yo me guie por lo que ya todas estas librerias estaban en el html. No se si me ayuda en decir en donde esta el "standalone", por lo que busque el proyecto y no logro encontrarlo.

2016-12-03 02:34 UTC, lglopezf commented on app/scripts/controllers/items-controller.js
> +        create: false,
Exacto, asi estoy enviando yo las categorias. Cuando voy a crear o actualizar un producto, le adjunto al producto la lista de categorias (asi esta en productos):
**itemsVm.item.imagenes**, en mi caso es **itemsVm.item.categorias**. Tengo una pregunta. Sugun entiendo, puedo crear categorias si no existe, Pero todo se guarda en cascada cuando envio el producto o  se crea en ese momento la categoria?

2016-12-03 02:37 UTC, lglopezf commented on app/scripts/controllers/items-controller.js
> +        valueField: 'id',
@macool Ayudame con esta interrogante. No tengo muy claro el esceneario con este solicitud

2016-12-03 04:46 UTC, macool commented on app/scripts/controllers/items-controller.js
> +        create: false,
@lglopezf ese momento se crearía la categoría - voy a trabajar en el backend lo antes posible

2016-12-03 04:48 UTC, macool commented on app/index.html
> +    <script src="bower_components/angular-selectize2/dist/angular-selectize.js"></script>
@lglopezf sírvase

https://github.com/selectize/selectize.js#installation-and-files

<img width="797" alt="screen shot 2016-12-02 at 11 47 48 pm" src="https://cloud.githubusercontent.com/assets/1407000/20856878/d24b881a-b8e9-11e6-99b5-1ffdf6968ca5.png">

2016-12-03 10:34 UTC, fabricioflores commented on app/index.html
> +    <script src="bower_components/angular-selectize2/dist/angular-selectize.js"></script>
@macool eso es solo selectize... no de aguiular... pero si tienes razón en q hay un standalone :P...
@lglopezf ```<link rel="stylesheet" href="bower_components/selectize/dist/css/selectize.default.css ">
<script type="text/javascript" src="bower_components/jquery/jquery.js"></script>
<script type="text/javascript" src="bower_components/selectize/dist/js/standalone/selectize.min.js"></script>
<script type="text/javascript" src="bower_components/angular/angular.js"></script>
<script type="text/javascript" src="bower_components/angular-selectize2/dist/selectize.js"></script>````
http://machineboy2045.github.io/angular-selectize/ supongo q esta es la librería... como ya tenemos angular y jquery solo tendrías q agregar ese selectize y el angular selectize

2016-12-03 10:35 UTC, fabricioflores commented on app/scripts/config/translations-config.js
> +        categorias: 'Categorias',
typo... `Categorías`

2016-12-03 10:38 UTC, fabricioflores commented on app/scripts/controllers/items-controller.js
> +        create: false,
@lglopezf siempre te va a devolver lo que estás guardando, en este caso un item... creo q podrías dejarlo pendiente a esto hasta tener la documentación del api de como enviarse...

2016-12-03 10:39 UTC, fabricioflores commented on bower.json
> +    "angular-selectize2": "^3.0.1"
también veo en la documentación que agregando solo angular-selectize2, va a descargar las dependencias... 
http://machineboy2045.github.io/angular-selectize/#install

2016-12-03 14:54 UTC, lglopezf commented on app/scripts/config/translations-config.js
> +        categorias: 'Categorias',
Okey cambiado.

2016-12-03 15:07 UTC, lglopezf commented on app/index.html
> +    <script src="bower_components/angular-selectize2/dist/angular-selectize.js"></script>
@macool  @fabricioflores . Se quito la libreria http://machineboy2045.github.io/angular-selectize/, para solo utilizar la libreria selectize. Procedi a crear una directiva, para manejarlo de mejor manera.

2016-12-03 15:08 UTC, lglopezf commented on app/scripts/controllers/items-controller.js
> +      selectize();
Estoy simulando en el proximo commit que las categorias y las configuraciones voy a traerlo del backend

2016-12-03 15:09 UTC, lglopezf commented on bower.json
> +    "angular-selectize2": "^3.0.1"
Si ya se quito la libreria, para solo trabajar con selectize.

2016-12-03 16:04 UTC, lglopezf commented on app/index.html
> +    <script src="bower_components/angular-selectize2/dist/angular-selectize.js"></script>
Otra cuestión, en el html ubico solo esta linea:
<script src="bower_components/selectize/dist/js/standalone/selectize.min.js"></script>
Pero **cuando se ejecuta grunt serve**, se reemplaza automáticamente por estas tres lineas:

- <script src="bower_components/sifter/sifter.js"></script>
- <script src="bower_components/microplugin/src/microplugin.js"></script>
- <script src="bower_components/selectize/dist/js/selectize.js"></script>

Esto creo yo que hace automaticamente selectize.

2016-12-04 21:13 UTC, macool commented on app/styles/item/item.scss
> +}
yo me deshice de esta hoja de estilos en https://github.com/noggalito/porttare-frontend/pull/136/files#diff-3253b167b4e6a78b1c57557277e86f59

2016-12-07 08:02 UTC, fabricioflores commented on app/index.html
> +    <script src="bower_components/selectize/dist/js/selectize.js"></script>
no había el selectize q incluía todo?

2016-12-07 08:04 UTC, fabricioflores commented on app/scripts/controllers/items-controller.js
> +
xq tantos espacios?

2016-12-07 08:06 UTC, fabricioflores commented on app/scripts/directives/selectize/selectize.js
> +      link: function(scope, elemento, attrs) {//jshint ignore:line
También hay como agregar controllerAs https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#directives-and-controlleras
y hagámoslo en el controlador, no en link...

2016-12-07 08:07 UTC, fabricioflores commented on app/scripts/services/items-service.js
> +      CategoriesService.getCategories().then(function success(resp){
las categorías las lanzo desde el menú con un broadcast... por si las necesitas... @macool crees q ahí necesite manejar algo así como lo q hicimos en cateogories y el menú?

2016-12-07 08:08 UTC, fabricioflores commented on app/styles/item/form.scss
> +    border-radius: 24px 24px 24px 24px;
si pones una sola vez 24px se aplica 24 para todos los lados...

2016-12-08 01:13 UTC, lglopezf commented on app/styles/item/item.scss
> +}
Okey, eliminado.

2016-12-08 01:14 UTC, lglopezf commented on app/scripts/controllers/items-controller.js
> +
Okey. Cambiado

2016-12-08 01:16 UTC, lglopezf commented on app/styles/item/form.scss
> +    border-radius: 24px 24px 24px 24px;
Okey.

2016-12-08 01:28 UTC, lglopezf commented on app/index.html
> +    <script src="bower_components/selectize/dist/js/selectize.js"></script>
Esta linea se suponia que incluia todo que esta en standalone. 
**<script src="bower_components/selectize/dist/js/standalone/selectize.min.js"></script>**

Pero cuando se ejecuta grunt serve, se reemplaza automáticamente por estas tres lineas:

- <script src="bower_components/sifter/sifter.js"></script>
- <script src="bower_components/microplugin/src/microplugin.js"></script>
- <script src="bower_components/selectize/dist/js/selectize.js"></script>

2016-12-08 01:50 UTC, lglopezf commented on app/scripts/directives/selectize/selectize.js
> +      link: function(scope, elemento, attrs) {//jshint ignore:line
Lo hice ahi en link por lo que ahi me  llega el ELEMENTO, por lo que al elemento debo agregar las categorias.
function(scope, **elemento**, attrs) {
        var selectize = **elemento**.selectize(scope.config)[0].selectize;
        angular.forEach(scope.options, function(tag) {
         **selectize.addOption(tag);**
        });
      }

2016-12-12 15:31 UTC, fabricioflores commented on app/scripts/services/items-service.js
> +      };
xq está aquí esto de selectize? preferiría q esté en el controlador

2016-12-12 15:32 UTC, fabricioflores commented on app/scripts/directives/selectize/selectize.js
> +        var selectize = elemento.selectize(scope.config)[0].selectize;
q pasa si este arreglo en algún punto se modifica y ya no es la posición [0]? me gustaría una implementación a prueba de errores...

2016-12-13 01:36 UTC, macool commented on app/scripts/services/items-service.js
> +      CategoriesService.getCategories().then(function success(resp){
@lglopezf podemos cambiar el nombre para que no hayan confusiones? estas son ProviderItemCategories - las otras son ProviderCategories

2016-12-13 01:37 UTC, macool commented on app/scripts/services/items-service.js
> +      CategoriesService.getCategories().then(function success(resp){
@fabricioflores el problema es que nadie se ha tomado la molestia de entender por qué tienen un prefijo los modelos en el api

2016-12-13 01:39 UTC, macool commented on app/styles/item/form.scss
> +}
y pega un screenshot si haces css - yo preferiría que hagas sólo funcionalidad

2016-12-13 01:39 UTC, macool commented on app/styles/item/item.scss
> +}
sigo viendo esta hoja

2016-12-13 01:41 UTC, lglopezf commented on app/scripts/services/items-service.js
> +      CategoriesService.getCategories().then(function success(resp){
@macool. Lo utilice a este por lo que no estava el API todavia. Ahora ya debo consumir este endpoint GET /api/provider/item_categories

2016-12-13 01:46 UTC, lglopezf commented on app/scripts/services/items-service.js
> +      };
lo que pasa es que @macool , yo le entendi que queria que estas opciones retorne de un endpoint. Por eso simule este servicio. Pero primero estava en el controlador.

2016-12-13 01:53 UTC, macool commented on app/scripts/services/items-service.js
> +      };
@lglopezf las categorías de los productos del proveedor vienen desde el backend, tiene su propio endpoint

2016-12-13 10:04 UTC, fabricioflores commented on app/scripts/controllers/items-controller.js
> +
todavía están aquí....

2016-12-13 13:20 UTC, macool requested changes

2016-12-13 13:20 UTC, macool commented on app/scripts/config/translations-config.js
> +        type: 'Categorias',
type debería ser palabra reservada en JS. 
no te inventes propiedades, el modelo no se llama así

2016-12-13 13:20 UTC, macool commented on app/scripts/directives/selectize/selectize.js
> +        };
estos métodos no son genéricos para una librería de selectize. son específicos. podemos moverlos a otro lugar (tal vez el controlador) o podemos renombrar la directiva para que no sea general sino específica

2016-12-13 13:20 UTC, macool commented on app/scripts/services/items-service.js
> +      getSelectizeItemsCategorias:getSelectizeItemsCategorias
es un modelo distinto, alguna razón para no tener su propio servicio?

2016-12-13 13:22 UTC, macool commented on app/scripts/controllers/provider/item-controller.js
> +        launchModalShow();
:wat: bloqueamos la interfaz hasta que el api responda con las categorías?

2016-12-13 13:55 UTC, lglopezf commented on app/scripts/controllers/provider/item-controller.js
> +        launchModalShow();
Si, por lo que,  **si se llama a las categorías y a mostrar el modal como funciones independientes, no se cargan las configuraciones del selectize**. Otra opción era inicializar el selectize cuando se carga el controlador, y no el modal. Pero mejor me parecio esta solución.

2016-12-13 13:56 UTC, macool commented on app/scripts/controllers/provider/item-controller.js
> +        launchModalShow();
no es aceptable. el modal se muestra inmediatamente después de presionar el botón de edición

2016-12-13 13:59 UTC, lglopezf commented on app/scripts/services/items-service.js
> +      getSelectizeItemsCategorias:getSelectizeItemsCategorias
Por lo que estaba relacionado a items. Pero okey, ya lo cambio

2016-12-13 14:07 UTC, lglopezf commented on app/scripts/config/translations-config.js
> +        type: 'Categorias',
No es que me invento, Anteriormente estaba esto:

-  categorias: 'Categorias', y

@fabricioflores me puso este comentario

- typo...Categorías

Yo entendí que debía cambiar a tipo. Pero no hay problema, lo cambio, ha como estaba anteriormente.

2016-12-13 14:08 UTC, macool commented on app/scripts/config/translations-config.js
> +        type: 'Categorias',
.type no es correcto

deberías utilizar los prefijos que tiene el api. este modelo se llama 'provideritemcategory', no 'type'

2016-12-13 14:17 UTC, lglopezf commented on app/scripts/controllers/provider/item-controller.js
> +        launchModalShow();
entonces cargo las configuraciones cuando se carga el controlador. Las configuraciones del selectize deben estar inicializadas antes de que se cargue el modal.

2016-12-13 14:24 UTC, lglopezf commented on app/scripts/config/translations-config.js
> +        type: 'Categorias',
Okey, lo cambio, solo que si lo ubique fue por algo, por los comentarios anteriores. Gracias.

2016-12-13 14:42 UTC, fabricioflores commented on app/scripts/config/translations-config.js
> +        type: 'Categorias',
@lglopezf typo significa q está mal escrito... debe tener tilde `Categorías`

2016-12-13 14:57 UTC, lglopezf commented on app/scripts/config/translations-config.js
> +        type: 'Categorias',
okey gracias @fabricioflores

2016-12-14 19:16 UTC, lglopezf commented on app/scripts/directives/selectize/selectize.js
> +        };
Okey, cambie el nombre de la directiva a selectize-item-category.

2016-12-14 19:45 UTC, fabricioflores commented on app/scripts/directives/selectize/selectize-provider-item-category.js
> +        var selectize = elemento.selectize(scope.config)[0].selectize;
sigue existiendo este [0] aquí

2016-12-14 19:49 UTC, fabricioflores commented on app/scripts/directives/selectize/selectize-provider-item-category.js
> +        selectize.on('item_remove', itemRemove);
probaste si estos eventos se lanzan? me acuerdo q cuando no eran eventos propios del scope de angular tocaba forzar el digest...

2016-12-14 19:49 UTC, fabricioflores commented on app/scripts/directives/selectize/selectize-provider-item-category.js
> +        var itemRemove= function(value){
estamos definiendo `function itemRemove(value)`, no guardando la función en una variable

2016-12-14 19:51 UTC, fabricioflores commented on app/scripts/services/item-categories-service.js
> +    }
en cuantos lugares se llama este evento? o sino sería mejor tenerlo en el controlador, ya que son `data services` en su mayoría todos...

2016-12-14 19:52 UTC, fabricioflores commented on app/templates/item/new-edit.jade
> +            placeholder='Seleccione una categoría')
está genial esto...

2016-12-14 22:20 UTC, macool commented on app/scripts/controllers/items-controller.js
> +          getProviderItemCategories();
cuándo estamos haciendo getProviderItemCategories? no deberíamos consultar más veces de las necesarias

2016-12-14 23:18 UTC, lglopezf commented on app/scripts/directives/selectize/selectize-provider-item-category.js
> +        selectize.on('item_remove', itemRemove);
Si, por lo que si no funcionan estos eventos, no funcionaria la asignación de la categoria al producto. Lo proble varias varias veces.

2016-12-14 23:19 UTC, lglopezf commented on app/scripts/services/item-categories-service.js
> +    }
en dos controladores ItemsController (crear un producto) y en ProviderItemController (editar producto)

2016-12-14 23:24 UTC, lglopezf commented on app/scripts/controllers/items-controller.js
> +          getProviderItemCategories();
se ejecuta cuando se inicia el controlador, pero aqui tambien, por lo pueda ocurrir que se creó una categoria nueva. Necesito tener actualizado las categorias a fin que si el usuario decide actualizar nuevamente el producto, este en la lista la categoria que se creo recien.

2016-12-15 01:28 UTC, lglopezf commented on app/scripts/directives/selectize/selectize-provider-item-category.js
> +        var itemRemove= function(value){
Segun entiendo, debo cambiar a esta forma. Okey 
function itemRemove(value){
}

2016-12-15 01:56 UTC, lglopezf commented on app/scripts/directives/selectize/selectize-provider-item-category.js
> +        var selectize = elemento.selectize(scope.config)[0].selectize;
@fabricioflores necesito hacer esto, por lo que es propio de la libreria selectize para que funcion los eventos propios de la libreria. Se puede hacer de esta forma:
var selectize = elemento.selectize(scope.config);
var control = selectize[0].selectize;
Yo estoy haciendo en una sola linea. Ahora la variable control es la que tiene los eventos addOption, addItem....
Dejo un link de referencia:
https://github.com/selectize/selectize.js/blob/master/examples/api.html
https://github.com/selectize/selectize.js/blob/master/docs/api.md

2016-12-15 13:48 UTC, fabricioflores commented on app/scripts/directives/selectize/selectize-provider-item-category.js
> +        var selectize = elemento.selectize(scope.config)[0].selectize;
q feo seleccionar así... jajajaja

2016-12-15 13:49 UTC, fabricioflores approved these changes
@macool de mi parte lo veo bien

2016-12-17 11:47 UTC, fabricioflores commented
@lglopezf solo solucionar conflictos de mi parte... 
@macool esto está listo para merger creo

2016-12-18 12:19 UTC, macool commented
:shipit:

2016-12-18 12:41 UTC, merged