Latitud longitud in address
noggalito/porttare-frontend pull request #185
Opened 2016-12-22 05:03 UTC by MarioRDuque

La nueva version de la Api gMaps incluye más librerías que antes 👎

2016-12-22 07:58 UTC, fabricioflores commented
@macool no sé mucho de gMaps... la implementación al menos en código parece estar bien...

2016-12-23 15:46 UTC, macool commented on app/scripts/app.js
> +    'uiGmapgoogle-maps'
vi que ya no es mantenida - no sé por qué la necesitas?

2016-12-23 15:46 UTC, macool commented on app/scripts/config/gmaps-config.js
> +        libraries: 'weather,geometry,visualization,places'
weather también?

2016-12-23 15:47 UTC, macool commented on app/scripts/controllers/profile/profile-update-addresses-controller.js
> +    };
no deberíamos escribirlos 2 veces - tampoco entiendo qué es?

2016-12-23 15:47 UTC, macool requested changes

2016-12-23 15:47 UTC, macool commented on app/styles/forms/resource-form.scss
> +      width: 500px;
width: 100%

2016-12-23 15:47 UTC, macool commented on app/templates/profile/addresses/form_template.jade
> +        ui-gmap-google-map(center='pfaVm.map.center' zoom='12' draggable="true" options="options")
no tenemos nuestras propias directivas?

2016-12-23 15:54 UTC, MarioRDuque commented on app/scripts/app.js
> +    'uiGmapgoogle-maps'
Es parte de la configuracion de angular gMaps. Aunque vi que en establecimientos usaron gMaps con #id

2016-12-23 15:56 UTC, MarioRDuque commented on app/scripts/controllers/profile/profile-update-addresses-controller.js
> +    };
Pues es el zoom con el que se debe mostrar el mapa.

2016-12-26 18:02 UTC, MarioRDuque commented
Existe un controlador map-controller.js; en base a ese controlador se creo la directiva maps y se le añadió el evento click al mapa. El resultado fue:

![latlng](https://cloud.githubusercontent.com/assets/10202966/21485065/cf1a9594-cb6a-11e6-8dc2-aac9088c04a1.gif)

Las coordenadas pasan asi:

![image](https://cloud.githubusercontent.com/assets/10202966/21485101/77985d3c-cb6b-11e6-82be-9dd3c26026fa.png)

2016-12-27 02:30 UTC, macool commented
@MarioRDuque al crear una nueva dirección, en caso de que no consigamos la ubicación actual podríamos tomar como sugerencia la dirección 1 del formulario actual.

caso contrario, obtenemos la ubicación mediante GPS - al momento de crear una dirección supongo

2016-12-27 15:26 UTC, MarioRDuque commented
Funcionamiento: 
   - Cuando la llamada es para crear, se muestra tu posición actual. 
   - Cuando la llamada es para editar: Si encuentra latitud y longitud muestra el marcador en esa posición, sino encuentra posición usa el servicio renderAddressMark para buscar la dirección_uno y mostrar ahí el marcador.
   - Los campos ciudad y direccion uno se completan segun el marcador pero con algo de retraso(alguna sugerencia?)
   - Veo la posibilidad de agregar una opción de eliminar el marcador en caso el usuario desista de usar el mapa.

2016-12-27 15:43 UTC, macool commented on app/templates/profile/addresses/form_template.jade
> +      maps(data="pfaVm.addressFormData" modo-update="pfaVm.inUpdateMode")
la directiva debe recibir lat/lon, no formData

2016-12-27 15:48 UTC, macool commented on app/scripts/directives/maps/maps.js
> +    function loadPlacesSearchBox(map) {
places debería ser una directiva nueva?

2016-12-27 16:06 UTC, macool commented on app/scripts/directives/maps/maps.js
> +        modoUpdate: '='
defaultInCurrentGeolocation

2016-12-27 23:49 UTC, macool commented on app/scripts/directives/maps/maps.js
> +              switch (err.code) {
esto es lógica del geoposicionamiento, que vaya en ese servicio

2016-12-28 04:02 UTC, MarioRDuque commented on app/scripts/directives/maps/maps.js
> +              switch (err.code) {
Tomado

2016-12-28 17:23 UTC, macool commented on app/scripts/services/geolocation-service.js
> +          return $q.reject(message);
y si en lugar de esto retornas message no es lo mismo?

2016-12-28 17:26 UTC, MarioRDuque commented on app/scripts/services/geolocation-service.js
> +          return $q.reject(message);
si retorno solo message entra al succes. Es porque el servicio no reconoce que es un error sino no lleva el $q.reject

2016-12-29 01:29 UTC, macool commented on app/scripts/directives/maps/maps.js
> +                }
no es óptimo que generes un objeto con propiedades vacías - seguro no necesitas hacerlo

2016-12-29 02:00 UTC, macool commented on app/scripts/directives/maps/maps.js
> +      if (useMarker) {
mejor deshacerse de este argumento y hacer un nuevo método

2016-12-29 02:01 UTC, macool commented on app/scripts/directives/maps/maps.js
> +                handleLocationError(message, defaultPosition, false);
no quiero que nuestros nuevos métodos tengan que ser complejos porque la vieja implementación no es flexible

2016-12-30 15:47 UTC, macool commented on app/scripts/directives/maps/maps.js
> +    mapVm.addMarker = addMarker;
por qué está expuesto?

2016-12-30 16:57 UTC, macool commented
tomo este branch

2016-12-31 19:29 UTC, merged