Vista de total, subtotal de la orden por proveedor-Comprador
noggalito/porttare-frontend pull request #233
Opened 2017-01-19 23:59 UTC by lglopezf

2017-01-20 13:26 UTC, fabricioflores approved these changes

2017-01-23 21:21 UTC, macool commented on app/scripts/controllers/customer/orders/customer-order-controller.js
> +      angular.forEach(provider.customer_order_items, function (item) {// jshint ignore:line
reduce

2017-01-23 21:21 UTC, macool commented on app/scripts/controllers/customer/orders/customer-order-controller.js
> +      angular.forEach(customerOrderVm.customerOrder.provider_profiles, function (provider) {// jshint ignore:line
estas 2 asignaciones podrían ser más claras

2017-01-23 21:21 UTC, macool commented on app/templates/customer/orders/show.jade
> -    .resource-collection
por qué se va resource-collection? esto no aplica estilos que necesitamos?

2017-01-24 01:59 UTC, lglopezf commented on app/scripts/controllers/customer/orders/customer-order-controller.js
> +      angular.forEach(provider.customer_order_items, function (item) {// jshint ignore:line
okey cambiado

2017-01-24 02:08 UTC, lglopezf commented on app/scripts/controllers/customer/orders/customer-order-controller.js
> +      angular.forEach(customerOrderVm.customerOrder.provider_profiles, function (provider) {// jshint ignore:line
okey. Cambiado

2017-01-24 02:09 UTC, lglopezf commented on app/templates/customer/orders/show.jade
> -    .resource-collection
si le probe y sin ello igual no afecto al diseño.

2017-01-24 05:03 UTC, macool requested changes

2017-01-24 05:03 UTC, macool commented on app/scripts/controllers/customer/orders/customer-order-controller.js
> +      return subTotalCentsOrderProvider;
:yuno: borra esta variable `subTotalCentsOrderProvider`

2017-01-27 11:43 UTC, merged

2017-01-27 11:43 UTC, macool commented
@lglopezf ayúdame a ver que el diff esté bien