Feature #891: proveedor - vista de oficinas en mi cuenta
noggalito/porttare-frontend pull request #238
Opened 2017-01-23 18:24 UTC by carito22

se corrigio bug de toggle, inactivo/activo , opaco cuando es inactivo

2017-01-23 21:15 UTC, macool commented on app/styles/offices/show.scss
> +    opacity:0.4;
puedes borrar esto? no es correcto

2017-01-23 21:16 UTC, macool commented on app/scripts/controllers/office-controller.js
> +        if (response.provider_office.enabled === 'No'){// jshint ignore:line
el api debe responder true/false, hay que revisar

2017-01-23 21:17 UTC, macool commented on app/templates/offices/detail.jade
> -              | {{ ::("office.weekdays.selectHourPlaceholder" | translate) }}
lo que debemos mostrar es el horario para cada día, igual que se muestra en el backend

2017-01-24 02:03 UTC, carito22 commented on app/scripts/controllers/office-controller.js
> +        if (response.provider_office.enabled === 'No'){// jshint ignore:line
esto es lo que me trae el api 
![image](https://cloud.githubusercontent.com/assets/13562862/22231089/477a2810-e1af-11e6-892f-77485c5b9023.png)

2017-01-24 02:03 UTC, carito22 commented on app/scripts/controllers/office-controller.js
> +        if (response.provider_office.enabled === 'No'){// jshint ignore:line
Si/No en letras no true/false

2017-01-24 02:06 UTC, carito22 commented on app/styles/offices/show.scss
> +    opacity:0.4;
porque no es correcto , entonces como haría que se haga opaco? si es inactivo

2017-01-24 05:01 UTC, macool commented on app/scripts/controllers/office-controller.js
> +        if (response.provider_office.enabled === 'No'){// jshint ignore:line
@carito22 no nos sirve si no tienes el api actualizado

<img width="800" alt="screen shot 2017-01-24 at 12 00 53 am" src="https://cloud.githubusercontent.com/assets/1407000/22234711/339cca96-e1c8-11e6-9058-e8083ffffb8d.png">

2017-01-24 12:33 UTC, fabricioflores commented on app/scripts/controllers/office-controller.js
> +      label:'Establecimiento Inactivo'
la identación está mal en label... un espacio de más

2017-01-26 14:59 UTC, fabricioflores commented on app/styles/offices/show.scss
> +
?

2017-01-27 23:12 UTC, macool commented on app/templates/offices/detail.jade
> +    ) {{officesVm.active.label}}
traduce esto en el template

2017-01-27 23:12 UTC, macool commented on app/scripts/controllers/office-controller.js
> +      label:'Establecimiento Inactivo'
traducir (de preferencia en el template)

2017-01-27 23:13 UTC, macool commented on app/scripts/controllers/office-controller.js
> +      officesVm.active = getActive();
:confused: no creo que tengas que hacer todo esto, deberías bindear el modelo, no?

2017-01-27 23:15 UTC, macool requested changes
mejor quitar la lógica de los controladores y en el template hacer una traducción simple para el estado activo o inactivo

2017-01-28 11:27 UTC, fabricioflores commented on app/scripts/controllers/office-controller.js
> +      officesVm.active = getActive();
si... definitivamente el binding con el modelo...

2017-01-28 11:27 UTC, fabricioflores commented on app/styles/offices/show.scss
> +
quita esto si está vacío...

2017-01-28 23:53 UTC, carito22 commented on app/styles/offices/show.scss
> +
ok

2017-01-30 13:00 UTC, fabricioflores commented on app/templates/offices/detail.jade
> +    ) {{(officesVm.officeDetail.enabled) ? ("office.officeEnabled"|translate) : ("office.officeDisabled"|translate) }}
xq no haces en las traducciones que office tenga officeEnabled y dentro tenga true o false. Así traduce directamente el `officesVm.officeDetail.enabled`

2017-01-30 13:00 UTC, fabricioflores commented on app/templates/offices/detail.jade
> +          ng-disabled="true"
siempre true?

2017-02-01 17:45 UTC, macool commented on app/templates/offices/detail.jade
> +          ng-disabled="true"
y mejor que no se vea, una clase .hidden o comentar //

2017-02-01 17:45 UTC, macool commented on app/templates/offices/detail.jade
> +          ng-disabled="true"
no tenemos api para esto 😒

2017-02-01 17:58 UTC, carito22 commented on app/templates/offices/detail.jade
> +          ng-disabled="true"
ok , entonces lo ocultare

2017-02-07 23:08 UTC, carito22 commented on app/templates/offices/detail.jade
> +    ) {{(officesVm.officeDetail.enabled) ? ("office.officeEnabled"|translate) : ("office.officeDisabled"|translate) }}
corregido

2017-02-16 03:24 UTC, merged