Select product
noggalito/porttare-frontend pull request #62
Opened 2016-09-19 01:30 UTC by daosgc

@fabricioflores @macool

2016-09-20 10:55 UTC, fabricioflores commented on app/scripts/config/routes.js
> +        controllerAs: 'productVm',
esa coma al final baja la calidad de código en CodeClimate... elimina y ya q copiaste y pegaste de la definición de otro estado"date" arreglando del resto de definiciones de estados. 
PD. Si, si haces blame estoy yo, es xq este archivo lo moví del `app.js` pero si quisiera averiguar también como comenzó esto de las comas...

2016-09-20 10:55 UTC, fabricioflores commented on app/scripts/controllers/product-controller.js
> +    productVm.product = {
Ya que esto va a venir del backend, y presumiblemente desde un servicio, mejor mockea está data en el servicio y has a el servicio responda esto con una promesa, y acá usas el controlador, así cuando ya esté el backend de productos solo cambia en el servicio

2016-09-20 10:55 UTC, fabricioflores commented on app/scripts/controllers/product-controller.js
> +    productVm.slickConfig = {
Los valores son los mismos de otro lado q vi por ahí? Si es así mejor hagamos una directiva con estos valores por defecto y así reutilizamos esos valores en ambos lados

2016-09-20 10:55 UTC, fabricioflores commented on app/templates/product/show.jade
> +        a.button.button-icon.icon.ion-minus-circled(ng-click="productVm.updatePrice('remove')")
no uses `<a>` cuando no son links... esto va a permitir "Abrir enlace en otra pestaña" y no va a llevar a ningún lado

2016-09-20 10:55 UTC, fabricioflores commented on app/scripts/config/routes.js
> +        controllerAs: 'productVm',
esa coma al final baja la calidad de código en CodeClimate... elimina y ya q copiaste y pegaste de la definición de otro estado"date" arreglando del resto de definiciones de estados. 
PD. Si, si haces blame estoy yo, es xq este archivo lo moví del `app.js` pero si quisiera averiguar también como comenzó esto de las comas...

2016-09-20 11:49 UTC, macool commented on app/scripts/config/routes.js
> +        controllerAs: 'productVm',
PD. PLGP

2016-09-20 11:49 UTC, macool commented on app/scripts/controllers/product-controller.js
> +    productVm.moreLabel = 'mostrar mas';
`mostrar mas`❓

2016-09-20 11:50 UTC, macool commented on app/scripts/controllers/product-controller.js
> +    productVm.moreLabel = 'mostrar mas';
1. el texto en el template
2. traducir

2016-09-20 11:51 UTC, macool commented on app/scripts/controllers/product-controller.js
> +    productVm.slickConfig = {
@fabricioflores que de hecho están mal porque no se ajustan a lo que especifican los bocetos

2016-09-20 11:51 UTC, macool commented on app/scripts/controllers/product-controller.js
> +        productVm.moreLabel = 'mostrar menos';
`mostrar menos` ❓

2016-09-20 11:52 UTC, macool requested changes
se ve bien!

2016-09-20 11:55 UTC, macool commented
@daosgc a esto también le falta backend verdad? El PM está al tanto de lo que estás haciendo? Porque ayer le consulté y no me mencionó que faltaba backend para esto

2016-09-20 14:25 UTC, daosgc commented on app/scripts/controllers/product-controller.js
> +        productVm.moreLabel = 'mostrar menos';
si algo que había en el boceto.. o lo meto dentro de las traducciones?? o en algunas contantes??

2016-09-20 14:26 UTC, daosgc commented
Hola @macool claro el si sabe, incluso por eso me asigno la otra tarea.. el si sabe que yo ya había acabado esta historia por el momento y falta la otra parte.. nose xq no te ha comentado nada

2016-09-20 14:27 UTC, macool commented on app/scripts/controllers/product-controller.js
> +        productVm.moreLabel = 'mostrar menos';
traducir :)

2016-09-20 14:30 UTC, daosgc commented on app/scripts/config/routes.js
> +        controllerAs: 'productVm',
jajajajajjaja esta bien ya lo hagoo..!!

2016-09-20 21:11 UTC, daosgc commented on app/scripts/controllers/product-controller.js
> +    productVm.slickConfig = {
pregunta.. que debo hacer entonces aqui??

2016-09-20 21:12 UTC, macool commented on app/scripts/controllers/product-controller.js
> +    productVm.slickConfig = {
@daosgc adherirte a los bocetos

2016-09-21 06:47 UTC, fabricioflores commented on app/scripts/controllers/product-controller.js
> +        productVm.moreLabel = 'mostrar menos';
xq mejor no usas un ng-if en el template y te evitas `productVm.moreLabel`, ahorita estás bindeando dos varaibles, si usas la bandera `productVm.more` solo la usarías una vez...

2016-09-21 06:48 UTC, fabricioflores commented on app/scripts/controllers/product-controller.js
> +    productVm.slickConfig = {
:macool:

2016-09-21 06:50 UTC, fabricioflores commented on app/scripts/config/routes.js
> +        controllerAs: 'productVm',
@macool esto salta en codeclimate pero no jshint, podemos integrar codeclimate en los PR?

2016-09-22 15:16 UTC, macool commented on app/scripts/config/translations-config.js
> +        less: 'montrar menos'
mostrar

2016-09-22 15:16 UTC, macool requested changes

2016-09-22 15:23 UTC, fabricioflores reviewed
y esta traducción?

2016-09-22 15:23 UTC, fabricioflores commented on app/templates/product/show.jade
> +          | Comprar Ahora
igual en traducciones

2016-09-26 11:17 UTC, fabricioflores commented
faltan test también

2016-09-26 12:48 UTC, daosgc commented
Así quedamos en que cuando este el back iba hacer los tests.. me parece que ya está asi que ya lo voy actualizar luego.. ah se sigue cayendo codeclimate en la primera linea @fabricioflores..

2016-09-26 13:06 UTC, fabricioflores commented
@daosgc haz `shibeis` con master... en master están los cambios y ya debería ignorar eso

2016-10-15 08:07 UTC, fabricioflores commented on app/scripts/controllers/product-controller.js
> +    productVm.showMore = function () {
toggleShow

2016-10-15 08:07 UTC, fabricioflores commented on app/scripts/controllers/product-controller.js
> +    productVm.updatePrice = function (opt) {
también define en la parte de arriba del archivo:
`productVm.updatePrice = updatePrice`
y acá abajo solo como función, eso para todas las funciones, así, en la parte superior sabemos que funciones están expuestas a la vista

2016-10-15 08:07 UTC, fabricioflores commented on app/templates/product/show.jade
> +              | Añadir al carrito
también en traducciones todos estos botones

2016-10-15 08:07 UTC, fabricioflores commented on app/styles/products/show.scss
> +    align-content: space-between;
😍

2016-10-15 08:09 UTC, fabricioflores commented on app/scripts/controllers/product-controller.js
> +    };
aquí solo cámbiale el nombre por toggleShow y pon algo así como `!productVm.more` o `productoVm.more = !productVm.more`, no estoy seguro si el primero lo asigna o solo lo cambia, pero el segundo si lo asigna

2016-10-15 08:09 UTC, fabricioflores commented on app/scripts/controllers/product-controller.js
> +    productVm.updatePrice = function (opt) {
^

2016-10-15 08:10 UTC, fabricioflores commented on app/scripts/services/products-service.js
> +    });
@Sjlmejia podrías devolver por el momento algo así en ese servicio que estás mockeando

2016-11-17 16:21 UTC, fabricioflores commented on app/scripts/services/products-service.js
> +    });
ya existe creo el backend de productos

2016-11-21 08:51 UTC, fabricioflores commented on app/scripts/services/products-service.js
> +  function getProduct() {
q mismo vamos a hacer con esto @macool ? quien lo termina?

2016-11-24 17:18 UTC, macool commented
_finally_

2016-11-24 17:19 UTC, merged